version: "3"
services:
  bitwarden:
    image: mprasil/bitwarden
    environment:
      - DOMAIN=https://bitwarden.$DOMAIN:443 #Définition du domaine requise pour U2F
      - SIGNUPS_ALLOWED=false #Desactive la possibilité de s'inscrire
      - INVITATIONS_ALLOWED=true #Autorise la possibilité d'inviter qqun
      - ADMIN_TOKEN=$ADMIN_TOKEN #Active la page d'administration
      - WEBSOCKET_ENABLED=true #Active les websocket
      - SMTP_HOST=$SMTPHOST
      - SMTP_FROM=$SMTPFROM
      - SMTP_PORT=$SMTPPORT
      - SMTP_SSL=true
      - SHOW_PASSWORD_HINT=true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $MYDIR/bitwarden:/data/:rw
    deploy:
      labels:
        - traefik.enable=true
        - traefik.web.frontend.rule=Host:bitwarden.$DOMAIN
        - traefik.web.port=80
        - traefik.hub.frontend.rule=Host:bitwarden.$DOMAIN;Path:/notifications/hub
        - traefik.hub.port=3012
        - traefik.hub.protocol=ws
        - traefik.docker.network=traefik_public
    networks:
        - traefik_public

networks:
  traefik_public:
    external: true
