## This docker-compose file is designed to be used as a template in portainer.
## It is widely (completely) inspired from the funkypenguin's cookbook.
## Don't miss his webpage: https://geek-cookbook.funkypenguin.co.nz
##
##
## This template can be set up in your portainer "App template".
## Don't forget to set the following environment variables:
## - PUID => user id that can read/write the media files.
## - PGID => group id that can read/write the media files.
## - DOMAIN => your DNS domainname ( example.com )
## - OAUTH2_PROXY_CLIENT_ID => please see https://github.com/bitly/oauth2_proxy
## - OAUTH2_PROXY_CLIENT_SECRET => please see https://github.com/bitly/oauth2_proxy
## - OAUTH2_PROXY_COOKIE_SECRET => Some random long string


version: '3'
services:

  lazylibrarian:
    image: thraxis/lazylibrarian-calibre:latest
    environment:
     - PUID=$PUID
     - PGID=$PGID
     - TZ=Europe/Paris
    volumes:
#     - /var/data/volumes/lazylibrarian:/config
     - $MYDIR/lazylibrarian-thraxis:/config
#     - /media/gmedia/Books:/books
     - $MYDIR/Calibre-lib:/books
     - /media/local/DlTmp/:/downloads
     - /media/gmedia/DlTmp/BooksImport:/autoimport
#     - /media/Books:/calibreFolder
    networks:
     - autopirate3_internal

  lazylibrarian_proxy:
    image: a5huynh/oauth2_proxy
    networks:
      - autopirate3_internal
      - traefik_public
    deploy:
      labels:
        - traefik.frontend.rule=Host:lazylibrarian.$DOMAIN
        - traefik.docker.network=traefik_public
        - traefik.port=4180
    volumes:
      - $MYDIR/authenticated-emails.txt:/authenticated-emails.txt
    command: |
      -cookie-secure=false
      -upstream=http://lazylibrarian:5299
      -redirect-url=https://lazylibrarian.$DOMAIN
      -http-address=http://0.0.0.0:4180
      -email-domain=$DOMAIN
      -provider=google
      -authenticated-emails-file=/authenticated-emails.txt
    environment:
      - OAUTH2_PROXY_CLIENT_ID=$OAUTH2_PROXY_CLIENT_ID
      - OAUTH2_PROXY_CLIENT_SECRET=$OAUTH2_PROXY_CLIENT_SECRET
      - OAUTH2_PROXY_COOKIE_SECRET=$OAUTH2_PROXY_COOKIE_SECRET
      
  calibre-web:
    image: technosoft2000/calibre-web
    volumes:
     - $MYDIR/Calibre-lib:/books
     - $MYDIR/calibre-web:/calibre-web/config
    environment:
     - PUID=1000
     - PGID=1000
     - USE_CONFIG_DIR=true
     - SET_CONTAINER_TIMEZONE=true
     - CONTAINER_TIMEZONE=Europe/Paris
     - TZ=Europe/Paris
     - LANG=fr_FR.UTF-8
     - LANGUAGE=fr_FR.UTF-8
     - LC_ALL=fr_FR.UTF-8
    networks:
     - autopirate3_internal
     - traefik_public
    deploy:
      labels:
       - "traefik.enable=true"
       - "traefik.docker.network=traefik_public"
       - "traefik.port=8083"
       - "traefik.frontend.rule=Host:calibre.$DOMAIN"

  calibre-server:
    image: cgspeck/docker-rdp-calibre
    volumes:
     - $MYDIR/Calibre-lib:/config
     - /media/gmedia/DlTmp/Books:/autoimport
    ports:
     - 18080:8080
     - 18081:8081
     - 3389:3389
    environment:
     - USER_ID=1000
     - GROUP_ID=1000
     - EDGE=0 #Mise à jour à chaque démarrage
     - WIDTH=1280
     - HEIGHT=720
     - TZ=Europe/Paris
    networks:
     - autopirate3_internal
     - traefik_public

  calibre-server_proxy:
    image: a5huynh/oauth2_proxy
    networks:
      - autopirate3_internal
      - traefik_public
    deploy:
      labels:
        - traefik.frontend.rule=Host:calibre-server.$DOMAIN
        - traefik.docker.network=traefik_public
        - traefik.port=4180
    volumes:
      - $MYDIR/authenticated-emails.txt:/authenticated-emails.txt
    command: |
      -cookie-secure=false
      -upstream=http://calibre-server:8080
      -redirect-url=https://calibre-server.$DOMAIN
      -http-address=http://0.0.0.0:4180
      -email-domain=$DOMAIN
      -provider=google
      -authenticated-emails-file=/authenticated-emails.txt
    environment:
      - OAUTH2_PROXY_CLIENT_ID=$OAUTH2_PROXY_CLIENT_ID
      - OAUTH2_PROXY_CLIENT_SECRET=$OAUTH2_PROXY_CLIENT_SECRET
      - OAUTH2_PROXY_COOKIE_SECRET=$OAUTH2_PROXY_COOKIE_SECRET

networks:
  traefik_public:
    external: true
  autopirate3_internal:
    external: true
