## This docker-compose file is designed to be used as a template in portainer.
## It is widely (completely) inspired from the funkypenguin's cookbook.
## Don't miss his webpage: https://geek-cookbook.funkypenguin.co.nz
##
##
## This template can be set up in your portainer "App template".
## Don't forget to set the following environment variables:
## - DOMAIN => your DNS domainname ( example.com )
## - OAUTH2_PROXY_CLIENT_ID => please see https://github.com/bitly/oauth2_proxy
## - OAUTH2_PROXY_CLIENT_SECRET => please see https://github.com/bitly/oauth2_proxy
## - OAUTH2_PROXY_COOKIE_SECRET => Some random long string

version: "3.0"

services:
  duplicati:
    image: linuxserver/duplicati:latest
    volumes:
     - /dev/log:/dev/log
     - /var/data/volumes/duplicati:/config
     - /tmp/backups:/backups
     - /:/source:ro
    deploy:
    networks:
      - internal
    environment:
      - PUID=$PUID
      - PGID=$PGID

  duplicati-proxy:
    image: a5huynh/oauth2_proxy
    networks:
      - internal
      - traefik_public
    deploy:
      labels:
        - traefik.frontend.rule=Host:duplicati.$DOMAIN
        - traefik.docker.network=traefik_public
        - traefik.port=4180
    volumes:
      - /var/data/volumes/authenticated-emails.txt:/authenticated-emails.txt
    command: |
      -cookie-secure=false
      -upstream=http://duplicati:80
      -redirect-url=https://duplicati.$DOMAIN
      -http-address=http://0.0.0.0:4180
      -email-domain=$DOMAIN
      -provider=google
      -authenticated-emails-file=/authenticated-emails.txt
    environment:
      - OAUTH2_PROXY_CLIENT_ID=$OAUTH2_PROXY_CLIENT_ID
      - OAUTH2_PROXY_CLIENT_SECRET=$OAUTH2_PROXY_CLIENT_SECRET
      - OAUTH2_PROXY_COOKIE_SECRET=$OAUTH2_PROXY_COOKIE_SECRET

networks:
  traefik_public:
    external: true
  internal:
    driver: overlay
    ipam:
      config:
        - subnet: 172.16.10.0/24
