## This docker-compose file is designed to be used as a template in portainer.
## It is widely (completely) inspired from the funkypenguin's cookbook.
## Don't miss his webpage: https://geek-cookbook.funkypenguin.co.nz
##
##
## This template can be set up in your portainer "App template".
version: "3"

services:
  shepherd:
    image: mazzolino/shepherd
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "traefik.enable=false"
    deploy:
      placement:
        constraints: [node.role == manager]

  docker-cleanup:
    image: meltwater/docker-cleanup:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker:/var/lib/docker
    deploy:
      mode: global
