## This docker-compose file is designed to be used as a template in portainer.
## It is widely (completely) inspired from the funkypenguin's cookbook.
## Don't miss his webpage: https://geek-cookbook.funkypenguin.co.nz
##
##
## This template can be set up in your portainer "App template".
## Don't forget to set the following environment variables:
## - PUID => user id that can read/write the media files.
## - PGID => group id that can read/write the media files.
## - MYDIR => the directory where you store permanent data for your stacks
## - DOMAIN => your DNS domainname ( example.com )

version: "3.0"

services:
  unifi:
    image: linuxserver/unifi-controller:latest
    volumes:
      - $MYDIR/unifi:/config
    deploy:
      labels:
        - traefik.tags=frontend
        - traefik.frontend.passHostHeader=true
        - traefik.admin.backend=unifi
        - traefik.frontend.rule=Host:unifi.$DOMAIN
        - traefik.docker.network=traefik_public
        - traefik.admin.port=8443
        - traefik.admin.protocol=https
        - traefik.frontend.headers.SSLRedirect=true
        - traefik.frontend.headers.STSSeconds=315360000
        - traefik.frontend.headers.browserXSSFilter=true
        - traefik.frontend.headers.contentTypeNosniff=true
        - traefik.frontend.headers.forceSTSHeader=true
        - traefik.frontend.headers.SSLHost=$DOMAIN
        - traefik.frontend.headers.STSIncludeSubdomains=true
        - traefik.frontend.headers.STSPreload=true
        - traefik.frontend.headers.frameDeny=true
    networks:
      - traefik_public
      - internal
    ports:
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 8081:8081
      - 8443:8443
      - 8843:8843
      - 8880:8880
      - 6789:6789
    environment:
      - PGID=$PGID
      - PUID=$PUID
      - TZ=Europe/Paris

networks:
  traefik_public:
    external: true
  internal:
    driver: overlay
    ipam:
      config:
        - subnet: 172.16.7.0/24
